
name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    
permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." 

jobs:
  
   
  
  notify_pull_request_google_chat:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Google Chat
        if: ${{ always() }} # Utilisez 'always' pour vous assurer que la notification est envoyée même en cas d'échec des étapes précédentes
        uses: SimonScholz/google-chat-action@main
        with:
          webhookUrl: ${{ secrets.GOOGLE_CHAT_URL }}
          title: ${{  'Déploiement réussi sur Thotify ! 🚀'  }}
          subtitle: ${{  'Il y à eu une erreur lors de la mise en ligne..' }}
          additionalSections: |
            [              
              {
                "header": "Détails de la fusion",
                "collapsible": true,
                "widgets": [
                  { "decoratedText": { "text": "- Titre du commit  : ${{github.event.commits[0].message}}" } },
                  { "decoratedText": { "text": "- Auteur : ${{ github.event.commits[1].author.username }}" } }
                ]
              },
            ]

